
# SEO settings
title: "kevinb"
title2: ".us" # default: ""
description: "Nerd Things"
keywords: "Site Reliability Engineer, SRE, DevOps, System Administration, Cloud, Linux, Automation, Chromebooks, ChromeOS, Philosophy, Hacking, Maker, AI, SciFi, Science Fiction"
url: https://kevinb.us # site url
baseurl:  null # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/kevinkbush/kevinkbush.github.io
disqus_shortname: 
twitter_username:
comments: false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Kevin Bush"
  job      : "Dad, Husband, Writer, Site Reliability Engineer, Nerd, Philosopher"
  bio      : "Exploring where Philosophy, Humanity, Automation, and Technology Collide"
  thumb    : /images/author.jpg
  email    : info@kevin.us
  url      : http://kevinb.us
  github   : http://github.com/kevinkbush
  twitter  : 
  facebook : 
  linkedin : http://linkedin.com/in/kevinkbush

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: 

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
